<center>
<div class="alert alert-block alert-info">
    <h1> </h1>
    <h1><font size="+3"> <b> Math340 HW </b> </font></h1>
    <h1><font size="+3"> <b> Programming in Mathematics </b> </font></h1>
    <h1><font size="+3"> <b> Due  2/21/24</b> </font></h1>
    
</div>
</center>

<br>



<center>
<font size="+2">
Department of Mathematics and Statistics <br> <br>
San Diego State University <br> <br>
Spring 2025
</font>
</center>








## Your Name: Victor Allen 

## Your ID: 132107570

## 1. Summary

- Wrote functions for the vector dot product, magnitude and cosine similaritys, then compared 7 vectors to each other and ouput the values as a matrix. 

- Compared Truncating and Rounding

- Scanned a wikipedia page for the term "butterfly effect" 

## 2. Methodology

1) I wrote the functions using the definitions I found online, and using for loops to traverse the input vectors. Created a dictionary with a name of a color and its corresponing vecotor, then allocated an output matrix, and used nested for loops to compare each vector to all the others, and stored the results in the matrix. Printed the matrix formatted to 3 decimal points using rounding. 

2) Answered the question about the differences between truncating and simmilarity, then answered a hypothedtical about what 1b. would have looked like if I had used truncation instead of rounding. 

3) Used the code provided to initialize and get a list of all the words in the wikipedia article. Allocated flag, and freq variables to scan the article for the term butterfly effect. Looped through all the words in the article, trimmed the word to remove punctuation that might be appened at the ends, like periods, commas, and parenthases. Set all the characters in the word to lower case, if the word then matched the string "butterfly" the flag was set to 1. If the flag was set to 1, in the next loop iteration, the word was trimmed and compared to "effect", if it matched, freq was incremented. Either way the flag was reset to 0. 

## 3. Code and Results (e.g., Tables, Figures, Outputs)

### Results for Question 1 (within a Markdown cell)

In [ ]:
# Question 1
# Add your code for Question 1 here (inside a code cell)
import numpy as np
import math

def dot(A,B):
    if(len(A) != len(B)):
        print(f"Dot Product of {A}, {B} not possible!")
        return
    
    product = 0

    for i in range(len(A)):
        product += A[i]*B[i]

    return product

def mag(A):
    sumSquares = 0
    for i in range(len(A)):
        sumSquares += A[i] ** 2
    
    return math.sqrt(sumSquares)

def cosSim(A,B):
   return dot(A,B) / (mag(A) * mag(B))

colors = {
    "red" : [255,0,0],
    "orange": [255,165,0],
    "yellow": [255,255,0],
    "green": [0,128,0],
    "blue":[0,0,255],
    "indigo":[75,0,130],
    "violet":[128,0,128]
}

n = len(colors)
colorNames = list(colors.keys())
simMatrix = np.zeros((n,n))

for i in range(n):
    for j in range(n):
        simMatrix[i][j] = cosSim(colors[colorNames[i]], colors[colorNames[j]])


formatted_matrix = np.array2string(simMatrix, formatter={'float_kind': lambda x: f"{x:.3f}"})

print(formatted_matrix)
# Run the cell to display your results

[[1.000 0.840 0.707 0.000 0.000 0.500 0.707]
 [0.840 1.000 0.978 0.543 0.000 0.420 0.594]
 [0.707 0.978 1.000 0.707 0.000 0.353 0.500]
 [0.000 0.543 0.707 1.000 0.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 1.000 0.866 0.707]
 [0.500 0.420 0.353 0.000 0.866 1.000 0.966]
 [0.707 0.594 0.500 0.000 0.707 0.966 1.000]]


### Results for Question 2 (within a Markdown cell)

Rounding to a digit... rounds to that digit, if the digit after is < 5 it gets rounded down to zero, and the digit before stays the same. 4.53 rounded to one digit is 4.5, but if the number is >= 5, the digit gets one added to it. 4.55 rounded to one digit is 4.6. 

Truncation just chops the extra digits off without rounding them. 4.53 and 4.55 truncated to 1 digit are both 4.5. 

In question 1b, I rounded the output to three decimal places, if I had chosen to truncate, the output would be a little different. 

### Results for Question 3 (within a Markdown cell)

In [18]:
import calendar

def print_month(year, month, offset, highlight = None):
    days_in_week = ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"]
    daysInMonth = calendar.monthrange(year, month)[1]

    print(f"   {calendar.month_name[month]} {year}")
    print(" ".join(days_in_week))

    for i in range(offset):
        print("   ", end = "")

    for i in range(daysInMonth):
        if( (i + offset) % 7 == 0):
            print("\n", end = "")
        
        if highlight != None and i + 1 == highlight:
                print(f"\033[1;32;40m{i + 1:2}\033[0m ", end="")
        else:
                print(f"{i + 1:2} ", end="")

print_month(2025, 10, 3, highlight=6)

   October 2025
Su Mo Tu We Th Fr Sa
          1  2  3  4 
 5  6  7  8  9 10 11 
12 13 14 15 16 17 18 
19 20 21 22 23 24 25 
26 27 28 29 30 31 

In [1]:
# Question 3
# Add your code for Question 3 here (inside a code cell)
import requests
from bs4 import BeautifulSoup
import re
import string

def trimPunct(word):

    # I am including words where effect is followed immediatley by some form of punctuation
    # "butterfly effect. butterfly effect, (butterfly effect), ect"
    word = word.strip(string.punctuation)


    # I am specifically ommiting the term "butterfly effects", uncomment this code to include it. 

    if word.endswith("s"):
        word = word[:-1]

    return word

url = "https://en.wikipedia.org/wiki/Butterfly_effect"

response = requests.get(url)

if response.status_code == 200:
    soup = BeautifulSoup(response.content, 'html.parser')
    
    content = soup.find(id = 'mw-content-text')

    text = content.get_text().lower()

    words = text.split()

    freq = 0
    flag = 0
    
    for word in words:
        word = trimPunct(word)

        if word == "butterfly":
            flag = 1
            continue

        if(flag == 1):
            if (word == "effect"):
                freq += 1
            flag = 0

    print("Frequency of the word 'Butterfly Effect' is:", freq)
else:
    print("Error: Unable to retrieve the web page")


# Run the cell to display your results

/Users/victorallen/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


Frequency of the word 'Butterfly Effect' is: 50
